### ISSUE TITLE
ERROR: Could not load project

### ISSUE THREAD

**Issue by OfficialStamper** [kayler-renslow/arma-dialog-creator#51]
### Version and Build
Type your version info **and** build number. (Version looks something like 1.0.0 and build is just a number)

### Summary
One or two concise sentences about the issue (i.e. "error on importing").

### Detail
com.kaylerrenslow.armaDialogCreator.data.xml.XmlParseException: Job sorting: Went through all jobs for an iteration and did nothing (this error prevents infinite loop)!jobs=:[com.kaylerrenslow.armaDialogCreator.data.xml.ControlClassXmlHelper$CreateCustomControlClassJob@3d40e51, com.kaylerrenslow.armaDialogCreator.data.xml.ControlClassXmlHelper$ControlExtendJob@46c76b9b]
	at com.kaylerrenslow.armaDialogCreator.data.xml.ProjectLoaderVersion1.loadProject(ProjectLoaderVersion1.java:81)
	at com.kaylerrenslow.armaDialogCreator.data.xml.ProjectLoaderVersion1.readDocument(ProjectLoaderVersion1.java:51)
	at com.kaylerrenslow.armaDialogCreator.data.xml.ProjectXmlLoader.parseProjectXmlFile(ProjectXmlLoader.java:46)
	at com.kaylerrenslow.armaDialogCreator.main.ArmaDialogCreator$1.call(ArmaDialogCreator.java:248)
	at com.kaylerrenslow.armaDialogCreator.main.ArmaDialogCreator$1.call(ArmaDialogCreator.java:237)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Job sorting: Went through all jobs for an iteration and did nothing (this error prevents infinite loop)!jobs=:[com.kaylerrenslow.armaDialogCreator.data.xml.ControlClassXmlHelper$CreateCustomControlClassJob@3d40e51, com.kaylerrenslow.armaDialogCreator.data.xml.ControlClassXmlHelper$ControlExtendJob@46c76b9b]
	at com.kaylerrenslow.armaDialogCreator.data.xml.ControlClassXmlHelper.sortJobs(ControlClassXmlHelper.java:98)
	at com.kaylerrenslow.armaDialogCreator.data.xml.ControlClassXmlHelper.runJobs(ControlClassXmlHelper.java:47)
	at com.kaylerrenslow.armaDialogCreator.data.xml.ProjectLoaderVersion1.loadProject(ProjectLoaderVersion1.java:77)
	... 7 more

THREAD:Arma Dialog Creator JavaFX Thread

**Comment by OfficialStamper** [comment]
Just renamed (restored) the custom_controls.backup.xml and the project loads now (phew).

custom_controls.backup.xml attached.
[custom_controls.xml.backup.zip](https://github.com/kayler-renslow/arma-dialog-creator/files/3751310/custom_controls.xml.backup.zip)

**Comment by kayler-renslow** [comment]
Thanks for the bug report. I'll take a look into this issue this week.
